### ISSUE TITLE
UserAddDto degisimi

### ISSUE THREAD

**Issue by 3ddark** [aliyasindogan/ECommerceProjectWithWebAPI#6]
Hocam c# acemisiyim. Öğrenmeye aşina olmaya çalışıyorum. Yıllardır Delphi kullandım. İlk kayıt olan eklenen user için istenen sınıf içindeki Token ve TokenExpireDate gereksiz duruyor.

**Comment by aliyasindogan** [comment]
Merhaba. Öneriniz için teşekkür ederim. 37-38 ve 39. videolarda yapıyı daha farklı bir şekilde ele alıyorum. Github a da kodları gönderdim.
