### ISSUE TITLE
CreateUserId ve UpdateUserId öneri 

### ISSUE THREAD

**Issue by 3ddark** [aliyasindogan/ECommerceProjectWithWebAPI#7]
Acemi olduğumu tekrar belirterek CreateUserId ve UpdateUserId bilgilerini token ile yapılan güvenlikli işlemlerde header bilgisi ilen gelen jwt içinden alabilir veya token ile kullanıcı tablosundan kullanıcı bulunabilir.

**Comment by aliyasindogan** [comment]
Merhaba. İleriki videolarda (37-38-39) da yapıyı farklı şekilde düzenliyorum. Teşekkürler
