### ISSUE TITLE
Entity Include

### ISSUE THREAD

**Issue by 3ddark** [aliyasindogan/ECommerceProjectWithWebAPI#8]
Yanlışım varsa şimdiden .Net ve EF kısmında acemiliğim olduğunu bildireyim.
İlişkili tablolarda gördüğüm kadarıyla Include kullanmadan gelmiyor. Bu şekilde gelmesini nasıl sağlayacağız. Burada Generic kısmında nasıl hareket edeceğiz.
```
  public class Product : AuditableEntity
  {
    public string ProductCode { get; set; }
    public string ProductName { get; set; }
    public int ProductGroupId { get; set; }
    public ProductGroup productGroup { get; set; }
  }

  public class ProductGroup : AuditableEntity
  {
    public string Group { get; set; }
  }
```
şeklinde bir yapımız var. Product tablosunda GetList yaptığımızda productGroup elemanının da dolu olarak gelmesini nasıl sağlayacağız.

@aliyasindogan Teşekkürler.

**Comment by aliyasindogan** [comment]
Merhaba, Product'a bir DTO oluşturmalısınız. Örnek ProductDetailDto gibi ve bunu EfProductDal kısmında listedeki istediğiniz kısmı doldurmalısınız. 
 public class ProductDetailDto
  {
    public int Id { get; set; }
    public string ProductCode { get; set; }
    public string ProductName { get; set; }
    public int ProductGroupId { get; set; }
    public string ProductGroupName  { get; set; }
  }

using(var context =new DbContext){
var result=from product in context.Products
join productGroup in context.ProductGroups in on product.productGroupId == productGroup.Id
select new ProductDetailDto{
Id=product.Id,
ProductGroupName=productGroup .GroupName,
.....
}
gibi bir örnek.
}
