### ISSUE TITLE
Http Status Codes

### ISSUE THREAD

**Issue by 3ddark** [aliyasindogan/ECommerceProjectWithWebAPI#9]
Yasin hocam Http Status kodlar için kendi oluşturduğunuz enum tipin içinde tanımlı olan kodları kullanmışsınız. Bunun yerine Microsoft.AspNetCore.Http içinde 
public static class StatusCodes
isimli class için tüm kodlar tanımlı buradan kullanmak daha kolay ve doğru gibi.

**Comment by aliyasindogan** [comment]
Merhaba, Hatırlatma için teşekkür ederim. StatusCodes yerine daha detaylandırma adına hata ve uyarı kodlar kullandığım için Microsoft.AspNetCore.Http kodlarını kullanmadım.
